### ISSUE TITLE
Add contact group and bidirectional relationship with contacts

### ISSUE THREAD

**Issue by alexopenline** [openline-ai/openline-customer-os#108]
Contact Group
- Name

Contact Group - CONTAINS -> Contact
Contact - BELONGS_TO -> Contact Group

**Comment by alexopenline** [comment]
@xvasi mutation AddContactToGroup will not fail if contact or group does not exists (in cypher).
I suggest we leave as is, 
  and add validations later for existence of contact / group if there will be a need.

**Comment by xvasi** [comment]
That's ok for now
