### ISSUE TITLE
Important UX Problems

### ISSUE THREAD

**Issue by avalot** [openline-ai/openline-customer-os#1123]
Finder: 

- [x] Merge organizations: The checkbox shouldn't be next to the Contact. It should be left of the organization name.
- [x] Merge contacts: The checkbox shouldn't be next to the email. It should be left of the contact name.

![image](https://user-images.githubusercontent.com/831133/222735935-97caee48-e7dd-46da-b933-324b38c8fab5.png)

Details:
- Back button should be just a backwards-caret icon (no text), in a round circle, 40x40, in the same position as the openline logo is on the meta panel.

- [x] Page should be aligned-left, not centered.

- the page contents (the two columns, three <Section>s) should be inside a container floating above the background. The page can use a random background from the blueprint theme. 

- [x] Spacing between the left column and right column (grid-gap) should be the same at all non-mobile breakpoints, not so big:
Bad: grid-gap: 120px
![image](https://user-images.githubusercontent.com/831133/222751690-74255531-07da-4bd4-b0dd-a81ba6c1390d.png)

Good: grid-gap: 24px
![image](https://user-images.githubusercontent.com/831133/222751782-ba204014-e2e7-4b63-9ba4-89f7fb5e06af.png)

- [x] Timeline needs to start right below the logger, not at the same vertical grid level as the Fieldsets.
![image](https://user-images.githubusercontent.com/831133/222754816-e57846d5-228d-4381-87bd-11758c936ef2.png)

- [x] The top of the timeline should have the heading: "{contact name/Unnamed contact/Org name} Timeline", with a bit of padding-right: (Note: this will go away once we move to new-at-bottom)
![image](https://user-images.githubusercontent.com/831133/222768494-b9624430-ed04-4688-8b35-6d7f2786eca9.png)

ID card:

-  #1154
-  #1155
-  #1146

Tags:
- [x] tag text should not be bold.
- [x] show the tag input as a limited-width box, saying "Add a tag...":
![image](https://user-images.githubusercontent.com/831133/222763347-995130ff-ae62-4dc8-b05f-4e24b2ec9ae0.png)

Fieldsets:

- [x] For primary fields, labels should not be bold (only values)

-  #1125

- [x] When adding an email / phone number, changing the type _before entering the value_ should not  save an empty value. Don't commit type until there is a value to save.

**Comment by Kasia9090** [comment]
> Timeline needs to start right below the logger, not at the same vertical grid level as the Fieldsets.

@avalot  shouldn't timeline be above the logger (according to the new message - reverse scroll principle)?

**Comment by Kasia9090** [comment]
> Page should be aligned-left, not centered.
this will be adressed later along with the design change

**Comment by Kasia9090** [comment]
> Page should be aligned-left, not centered.

Logger placed below timeline

**Comment by Kasia9090** [comment]
>  Spacing between the left column and right column (grid-gap) should be the same at all non-mobile breakpoints, not so big

grid gap for desktop - 44px

**Comment by Kasia9090** [comment]
>  It makes no sense that we ask for owner when editing, but don't show it on the card. Don't ask for owner during editing. We're not going to support the "owner" concept in Openline, since there's a timeline that shows you who's interacted with the contact. Like Forrest Gump would say: Owner is as owner does.

Owner Id is required to create contact. I'm moving it to separate issue
