### ISSUE TITLE
Moderate UX problems

### ISSUE THREAD

**Issue by avalot** [openline-ai/openline-customer-os#1124]
### META:
- [x] Clicking outside the expanded META panel (blurred area) should close the META panel:
![image](https://user-images.githubusercontent.com/831133/222737811-b45c0672-3135-41a1-98c4-155de0165d56.png)

### Details:

- [x] The ID card should have the minimum height corresponding to a 3:2 aspect ratio:
- [x] The ID card should be slightly skeuomorphized with a drop shadow:
![image](https://user-images.githubusercontent.com/831133/222920334-57af0904-259c-490d-9cc0-8c38b6fbed59.png)
For the styling above I used:
`
background: radial-gradient(hsla(200,30%,100%,.7) 30%,hsla(200,30%,97%,.9));
box-shadow: 2px 2px 4px -2px rgba(0,0,50,0.23),6px 6px 20px rgba(0,0,50,.10),-8px -8px 16px 2px hsla(200,0%,100%,.278);
`

- [x] Keep all text baselines aligned (vertically)
- [x] Keep all text lines left-aligned (horizontally), even when an icon is present:
![image](https://user-images.githubusercontent.com/831133/222919341-6efc600c-c0f5-4d79-a15c-cdced3edeb83.png)
- [x] Make that alignment match the one in the ID card:
![image](https://user-images.githubusercontent.com/831133/222919805-1c440d00-75cb-4164-83ab-a7585f277830.png)

**Comment by Kasia9090** [comment]
there is a hook `useDetectClickOutside` that can used for closing side panel on click outside
