### ISSUE TITLE
Emails and phone numbers must be editable. 

### ISSUE THREAD

**Issue by avalot** [openline-ai/openline-customer-os#1125]
Perhaps you don't commit to the back-end until blur (through click-out or enter key), and the back-end will need to create new nodes... either way. People have expectations that emails and phone numbers are editable, we have to acknowledge their will.

**Comment by Kasia9090** [comment]
@avalot The reason why edit is not enabled is not on FE side. We don't have mutation that allows to edit email. @alexopenline can explain better the reasons behind it.
The only thing that can be done is hacking on fe (deleting and adding new item without user knowledge) but I do not recommend that solution. It's very dirty and has risk of introducing bugs (eg. something is wrong while saving user loose connection -> in that case if deletion was successful data is lost)

**Comment by alexopenline** [comment]
Fixed backend in https://github.com/openline-ai/openline-customer-os/issues/1148
