### ISSUE TITLE
UI for displaying voice calls

### ISSUE THREAD

**Issue by avalot** [openline-ai/openline-customer-os#1134]
(wireframes here: https://www.figma.com/file/pLlrw4j1q98Tbdv3hafvZ0/Quick-Fix-wireframes?node-id=0%3A1&t=3xmDwizYfWdYwOxj-1 )

For voice calls in the timeline, let's show them as a heading line displaying:
- originator and receiver on either sides
- Channel used (in the middle)
- Direction of call (as a triangle emerging from color gradients, pointing at the receiver, on the receiver side)
- Clickable waveform icon to pull up the audio recording, followed by the time elapsed, on the sender side.

- Below that heading line, if available, a very short summary with a caret affordance. The whole summary area is click/tappable, and toggles the expansion/collapse of the transcript

- When displaying the transcript, do so on top of a "conversation drawer"
- display squarish bubbles on each side, indicating the speaker.
- If the speaker is ambiguous, display a bubble in the center (but the text remains left-aligned)
- If another interactionEvent (from another channel) happens in the middle of the call, display it in the middle of the call (but with its own visual style)

### Initiating a call, live transcription:

![image](https://user-images.githubusercontent.com/831133/223175326-b1f00673-7bbc-464e-90ab-90f1393469c1.png)

### Post-call transcription + summary:

After the call ends (and live transcription is probably late), remove the live transcript and replace it with the post-processing transcript. Keep the full transcript expanded. Add a summary line which toggles collapse/expand.

On subsequent loads of the page, show the conversation collapsed by default.

![image](https://user-images.githubusercontent.com/831133/223175466-01775f3c-38c5-430e-9b41-be58c77af712.png)

**Comment by Kasia9090** [comment]
> Post-call transcription + summary:
After the call ends (and live transcription is probably late), remove the live transcript and replace it with the post-processing transcript. Keep the full transcript expanded. Add a summary line which toggles collapse/expand. On subsequent loads of the page, show the conversation collapsed by default.

Moving this part to separate task as it does not fit into allocated timeframe
https://github.com/openline-ai/openline-customer-os/issues/1178

**Comment by Kasia9090** [comment]
@avalot time formatting should be changed to the one visible on wireframes or stay the same (as was requested in one of the ui improvements ticket)?
