### ISSUE TITLE
Data integrity issue

### ISSUE THREAD

**Issue by jontyk** [openline-ai/openline-customer-os#1164]
https://spaces.openline.ai/contact/509a47b5-379c-4436-9895-9a6527944968

<img width="962" alt="image" src="https://user-images.githubusercontent.com/81759836/223164209-9f2237ca-99ce-4a21-9780-b3c7d952b7c7.png">

Thank you for your bug report!  We ❤️ squashing 🪲

**Comment by Kasia9090** [comment]
Error message content:

```
[
    {
        "message": "Contact with id 509a47b5-379c-4436-9895-9a6527944968 not found",
        "path": [
            "contact"
        ]
    },
    {
        "message": "Result contains no more records",
        "path": [
            "contact"
        ]
    }
]
```

**Comment by edifirut** [comment]
@jontyk you are trying to access cross tenant information or information that doesn't exist. i'll close this and open another issue for a 404 page
