### ISSUE TITLE
Add tooltip with JSON of all page info (including not displayed info) to contact and org pages

### ISSUE THREAD

**Issue by jontyk** [openline-ai/openline-customer-os#1170]

**Comment by Kasia9090** [comment]
@jontyk I need more information about desired outcome. 
When this tooltip should appear (hovering on what element should trigger it). 
What is "all page info", eg.  does it include timeline? 
What not displayed info should be shown? 

Those are crucial as currently FE gets almost only informations necessary so I will need to prepare new query to get what is needed for tooltip

**Comment by avalot** [comment]
Need clarity on the problem we're trying to solve. Is this information not available in the browser inspector?

**Comment by jontyk** [comment]
Purpose is to display all available information to a power user or developer - currently it is not possible to understand all information or metadata related to a contact in the GUI. This will be exacerbated every time we add a new integration, thus knowing the underlying info allows a power user to identify what is missing from the GUI. Ultimately this is 'lazy' or 'nice to have' however will allow us to quickly and efficiently build the front end knowing all data available to us (as we will never display all the information to the user in the GUI).

@avalot the information is inherently not available in browser inspector as GraphQL does not fetch all data.
