### ISSUE TITLE
Edit email/phone number not working

### ISSUE THREAD

**Issue by jontyk** [openline-ai/openline-customer-os#1182]
Thank you for your bug report!  We ❤️ squashing 🪲

**Comment by Kasia9090** [comment]
@jontyk can you provide more information on how to reproduce this issue?

FYI: currently user can edit only label and primary property for email and contact. Please see the issue https://github.com/openline-ai/openline-customer-os/issues/1125

**Comment by alexopenline** [comment]
BE issue opened: https://github.com/openline-ai/openline-customer-os/issues/1148

**Comment by avalot** [comment]
Duplicate of https://github.com/openline-ai/openline-customer-os/issues/1125

**Comment by alexopenline** [comment]
update API enhanced with change or email / phone number: https://github.com/openline-ai/openline-customer-os/issues/1148
