### ISSUE TITLE
Waitlist broken on login screen

### ISSUE THREAD

**Issue by jontyk** [openline-ai/openline-customer-os#1187]
Add email to waitlist button missing. Also Login now! text has lost link decoration.

Thank you for your bug report!  We ❤️ squashing 🪲

**Comment by jontyk** [comment]
![image](https://user-images.githubusercontent.com/81759836/223478871-40e14c13-8edb-49e6-9fe9-a247a6867746.png)

**Comment by edifirut** [comment]
<img width="527" alt="image" src="https://user-images.githubusercontent.com/108661145/223542602-5c2b99bf-fd26-4ae3-b4b7-dfa48a489139.png">
