### ISSUE TITLE
Email response cannot be closed and carries over to other contacts

### ISSUE THREAD

**Issue by jontyk** [openline-ai/openline-customer-os#1193]
Thank you for your bug report!  We ❤️ squashing 🪲

**Comment by avalot** [comment]
Jonty can you please explain more / attach a sanitized screenshot?

**Comment by jontyk** [comment]
Click respond to any sent email on a contact/org, navigate away from that page and go to another contact/org, the notes section will be replaced with the email response from the original contact/org, requiring page refresh to not display that email editor.
