### ISSUE TITLE
Crash: Pages containing a Site Visit query.

### ISSUE THREAD

**Issue by avalot** [openline-ai/openline-customer-os#1197]
**Describe the bug**
On our tenant account,
Go to the page: https://spaces.openline.ai/contact/c3815f0a-6115-4673-ad84-cf9e1b7bde84
It crashes. Problem with the query. Please fix!

**Comment by Kasia9090** [comment]
@avalot I cannot reproduce the crash, are there any additional steps needed (besides entering the page)

**Comment by Kasia9090** [comment]
No longer reproducible
