### ISSUE TITLE
Add new contacts to customerOS

### ISSUE THREAD

**Issue by mattbr0wn** [openline-ai/openline-customer-os#12]

**Comment by matt-brown-OL** [comment]
As a customerOS user, I’d like the ability to add new contacts to customerOS.  All new contacts should have the ability to populate the following attributes:

- First name (text)
- Last name (text)
- Company name (text)
- Email (email)
- Phone number (e164)
- Contact type (single select)
  - Lead
  - Opportunity
  - Customer
  - (user defined)

**Comment by alexopenline** [comment]
@mattbr0wn  
As per model https://www.figma.com/file/eUzupmZZEQu5dwgVV3flDP/Customer-Os-Base-model?node-id=0%3A1 
Email and phone number to be extracted in separate node (Contact Details).
