### ISSUE TITLE
Better display for emails

### ISSUE THREAD

**Issue by avalot** [openline-ai/openline-customer-os#1228]
Let's make collapsed emails more scannable, and expanded emails more legible.

- [ ] Align all email labels right, make them gray and not-bold:
![image](https://user-images.githubusercontent.com/831133/223716375-d0e5308a-261a-453e-8d21-497c6512f94c.png)
![image](https://user-images.githubusercontent.com/831133/223717146-6dd1468d-3f15-49e0-a4da-ed21c4706346.png)

- [ ] Eliminate any blank lines at the top of the email message:
![image](https://user-images.githubusercontent.com/831133/223717461-c91527d0-0f3b-401c-b502-226ad936a45c.png)

- [ ] Bring the first line of the message closer to the top, and show one more line in the collapsed version:
![image](https://user-images.githubusercontent.com/831133/223717816-d80b789f-fbff-48c0-aef1-f09835d3c215.png)

**Comment by edifirut** [comment]
implemented
