### ISSUE TITLE
Lots of contacts in an org cause the add note/send email to go off screen and make whole screen scrollable

### ISSUE THREAD

**Issue by jontyk** [openline-ai/openline-customer-os#1235]
We should make contacts scrollable and constrain to screen height.

Thank you for your bug report!  We ❤️ squashing 🪲

**Comment by Kasia9090** [comment]
@jontyk desired outcome it that the whole details page is scrollable (native behaviour) or sections of those pages are (like eg. current timeline)?

**Comment by avalot** [comment]
Desired outcome:
- [ ] ID card is fixed.
- [ ] Logger is fixed. 
- [ ] Fieldsets are in a scrollable pane (if they're overflowing).
- [ ]Timeline is scrollable

![image](https://user-images.githubusercontent.com/831133/224066585-fdd544c6-1a37-41e2-a453-375f55487c61.png)


Also, ideally:
- [ ] Timeline display defaults to "now" (e.g. show it scrolled to the bottom)
