### ISSUE TITLE
Add user emails/phones to user profiles

### ISSUE THREAD

**Issue by jontyk** [openline-ai/openline-customer-os#1236]
Add user emails and phone numbers to user contact profiles/user profiles so that all tenant users can see their numbers.

Need discussion around contact/user split within tenants.

Thank you for your feature request!  We strive to make the product better every day, and your input helps!

**Comment by alexopenline** [comment]
@jontyk APIs updated to create / update / remove emails and phone numbers for Users.
Creating new issue to implement fetching phone number for user.

Leaving this task to handle UI part.
