### ISSUE TITLE
Improve Timeline UX

### ISSUE THREAD

**Issue by Kasia9090** [openline-ai/openline-customer-os#1256]
**Timeline UX needs improvements:**
-  Better email display https://github.com/openline-ai/openline-customer-os/issues/1358
- Better phone transcripts/summaries https://github.com/openline-ai/openline-customer-os/issues/1134
- Better notes https://github.com/openline-ai/openline-customer-os/issues/1344
- Better page views https://github.com/openline-ai/openline-customer-os/issues/1332
- Better site visits https://github.com/openline-ai/openline-customer-os/issues/1351
- Horizontally align the center of the contact avatar, and the edit button, with ← button: https://github.com/openline-ai/openline-customer-os/issues/1366

Please treat this ticket as a aggregate,  create separate tickets for each of of timeline item type 🙏

**Comment by avalot** [comment]
Work started today with Andrea to harmonize and improve these UIs
