### ISSUE TITLE
Improve UI of notes in organization

### ISSUE THREAD

**Issue by Kasia9090** [openline-ai/openline-customer-os#1291]
**Problem:**
- it's not clear if the note was logged against organization or contact
- [for contact] it's not clear against which contact activity was logged

**Comment by mattbr0wn** [comment]
![Screenshot 2023-03-15 at 13 14 39](https://user-images.githubusercontent.com/113338429/225320117-67e2d168-784d-4e47-bc55-39e449d8c5b7.png)

The two notes above were logged against a contact.  It's not at all clear what contact these notes belong to.  

Perhaps we need some sort of contact tagging system that tags all the contacts associated with the event?

**Comment by avalot** [comment]
Not clear either who wrote the note! :)

I'll work on that with Andrea.
