### ISSUE TITLE
Delay on data fetching when changing user between different tenants

### ISSUE THREAD

**Issue by jontyk** [openline-ai/openline-customer-os#1352]
**Describe the bug**
When switching between tenants there is a delay between which tenants data is returned to the user. This is likely related to changes from #1341 

**How to reproduce**
1. Log into Spaces
2. Logout
3. Log into Spaces with another user linked to another tenant
4. Data displayed will initially be old tenant

**Expected behavior**
When logging in and out between different users and tenants data should be refreshed using new user, not return data from user cache

Thank you for your bug report!  We ❤️ squashing 🪲

**Comment by edifirut** [comment]
fixed in https://github.com/openline-ai/openline-customer-os/pull/1354
