### ISSUE TITLE
"Display label" to give "Unnamed contact" a better name

### ISSUE THREAD

**Issue by avalot** [openline-ai/openline-customer-os#1374]
**Overview of the feature request and the problem you're looking to solve**
When all unnamed contacts are named "unnamed contact", it's a problem because:
- That's not a name, it's a label. If we show users that it's okay to put labels in name fields, they'll do it everywhere.
- It makes them all look the same
- It makes it hard to remember who an unnamed contact was, when you come back to rename it later, and you forgot why they were created.

**Describe the solution you'd like**
- [ ] We need a new field for contacts called "Display label". When we don't have a name, we show the display label, and it's styled differently (italics, gray). When we have a name, we show the name.
- [ ] On the contact details page, in edit mode, the Display label will not be editable (not user-editable), and will disappear whenever an actual name is entered. It will reappear if the name is removed.
- [ ] We should label the contact with the best possible label to achieve three goals:

1. Make it look different from other Unnameds.
2. Make it clear to everyone who created but didn't name the contact. Seeing your name on shared dirty data is a powerful motivator to clean it up.
3. Make it easy for the creator to rename the contact later, by giving them some context as to when it was created and why.  

For instance:
- [ ] When the user Bob Smith creates a new contact (through a phone call to an organization landline, for instance), but enter's no information, we should label it: "Bob Smith's contact from Feb 2 2023"
- [ ] When we're importing from a 3rd party system and we don't have a name, but we have an email, we put the email in the display label.
- [ ] When we're importing from a 3rd party system and we don't have a name or email, but we have a phone number, we put the phone number in the display label.
- [ ] When the contact came from a social media DM, we put in "@hellokitty2008 on Instagram" as the display name
- [ ] When we're importing a system record without a name, email, or phone, we should label it in a way that makes it easier to understand its provenance. "Requestor of Zendesk ticket: {ticket name}"

**Additional context**

Thank you for your feature request!  We strive to make the product better every day, and your input helps!

**Comment by hellokitty2008** [comment]
我已经收到您的邮件，尽快给您回复。

**Comment by hellokitty2008** [comment]
我已经收到您的邮件，尽快给您回复。
