### ISSUE TITLE
Differentiate Zendesk Support public reply and internal note on the timeline

### ISSUE THREAD

**Issue by jontyk** [openline-ai/openline-customer-os#1562]
**Overview of the feature request and the problem you're looking to solve**
Zendesk Support has 2 types of text input. Internal Note and Public Replies.
![image](https://user-images.githubusercontent.com/81759836/230362426-03a7073f-fa00-45bd-885e-08dd2aedadeb.png)

On the timeline we want to differentiate these via some styling. @avalot to provide.

**Describe the solution you'd like**
I want to see different styles of Zendesk comments on the timeline so I can differentiate if it is an internal note or a reply to the customer on that issue.

Thank you for your feature request!  We strive to make the product better every day, and your input helps!

**Comment by alexopenline** [comment]
@jontyk @Kasia9090
 
Adding public indicator to note, that is available in Zendesk on each comment as boolean with true / false
GrpahQL to be updated, each note will return new field public as boolean.

**Comment by alexopenline** [comment]
Public reply to be implemented as InteractionEvent: https://github.com/openline-ai/openline-customer-os/issues/1772
