### ISSUE TITLE
See Zendesk issue/ticket in context in timeline

### ISSUE THREAD

**Issue by jontyk** [openline-ai/openline-customer-os#1564]
**Overview of the feature request and the problem you're looking to solve**
When viewing the timeline of a customer (either an org or user), I want to see the entire lifecycle of that specific ticket easily in it's own context.

**Describe the solution you'd like**
This can either be done using a modal showing only that ticket that is scrollable to bring the entire (Jonty's preference), using permalinks (#1565) to move the timeline to previous/next or original ticket (Antoine's preference), or filtering/collapsing the timeline to only show the ticket with minimised events around it.

@avalot to have strong opinions on how we implement this (maybe multiple solutions).

Thank you for your feature request!  We strive to make the product better every day, and your input helps!

**Comment by Kasia9090** [comment]
All interaction events (eg. notes) shall be returned.
- Query by id for getting issue and all relevent content.
