### ISSUE TITLE
Add intial contact/org details to data layer and API

### ISSUE THREAD

**Issue by jontyk** [openline-ai/openline-customer-os#1839]
**Overview of the feature request and the problem you're looking to solve**
I want to be able to store metadata against a contact and an organization.

**Describe the solution you'd like**
- Contact
  - JobRoles (open question how does a personal email/phone number get added - is it a pseudo JobRole?)
    - Organization link
    - Role
    - Department
    - Division
    - Region
    - Email
    - Phone Number (and type of phone number)
    - Address (Location link)
  - Socials
    - LinkedIn
    - Twitter
    - Facebook
    - Instagram
  - Description
  - Tag
  - Owner
  - Stage (tenant set type)
  - `Custom Fieldsets`
- Organization
  - Website
  - Domains
  - Location
  - Email
  - Phone number
  - Ownership (Private/Public)
  - Funding Stage (Seed/Series A/Series B/.../IPO)
  - Socials
    - LinkedIn
    - Twitter
    - Crunchbase
  - Staff Number
  - Type
    - Store
    - Warehouse
    - HQ
    - Office
    - etc.
  - About/Description
  - Tag
  - Owner
  - Stage
  - `Custom Fieldsets`

**Additional context**

Thank you for your feature request!  We strive to make the product better every day, and your input helps!

**Comment by alexopenline** [comment]
Contact Description implemented in: https://github.com/openline-ai/openline-customer-os/issues/2036
