### ISSUE TITLE
Extract db interactions to separate repo from customer-data-api

### ISSUE THREAD

**Issue by alexopenline** [openline-ai/openline-customer-os#19]
Scope: split openline-customer-data-api in 2 parts:
* openline-customer-data-api - graphql server
* new repo - DB queries for modeled CDP data

**Comment by alexopenline** [comment]
During extraction GraphQL APIs to be remodeled to match new structure created in tracked-data-models project

**Comment by alexopenline** [comment]
New app to be written in GO

**Comment by mattbr0wn** [comment]
Let's make sure this aligns with the "standard" repo structure
