### ISSUE TITLE
neo4j cypher file not running in minikube

### ISSUE THREAD

**Issue by edifirut** [openline-ai/openline-customer-os#212]
**Describe the bug**
Given an empty environment, when you setup the infrastructure in minikube, [this file](https://github.com/openline-ai/openline-customer-os/blob/otter/packages/server/customer-os-api/customer-os.cypher) is not executed in neo4j

**How to reproduce**
1. minikube delete
2. ./0-mac-install-prerequisites.sh
3. ./1-deploy-customer-os-base-infrastructure-local.sh
4. ./2-build-deploy-customer-os-local-images.sh
5. check neo4j data: MATCH (t:Tenant) return t;

**Comment by edifirut** [comment]
Still not working as expected. I've followed the next steps:
- minikube delete
- ./0-mac-install-prerequisites.sh
- ./1-deploy-customer-os-base-infrastructure-local.sh
- ./2-build-deploy-customer-os-local-images.sh

**Comment by tsearle** [comment]
Please provide the output of 2
