### ISSUE TITLE
[Spaces] Contact shows wrong primary job in Contacts grid

### ISSUE THREAD

**Issue by jontyk** [openline-ai/openline-customer-os#2162]
**Describe the bug**
When a contact has no job title in a non-primary job, it will override the display of the primary job title and company in the Contacts grid view

**How to reproduce**
1. Create a user with a primary and secondary job at an org, don't give a job title to the secondary job
2. Navigate to the Contact grid and find this contact
3. See that the secondary job with no title is being displayed and not the primary job

**Expected behavior**
Always see the primary job title/org on the Contacts grid view.

Thank you for your bug report!  We ❤️ squashing 🪲

**Comment by Kasia9090** [comment]
Contact grid was removed
