### ISSUE TITLE
[api] User should be able to remove locations from Contact

### ISSUE THREAD

**Issue by Kasia9090** [openline-ai/openline-customer-os#2254]
**User should be able to remove locations:**
- If location is 1-1, delete node and link
- If location is 1-many, remove link

**Comment by shadow0500** [comment]
> **User should be able to remove locations:**
> 
> * If location is 1-1, delete node and link
> * If location is 1-many, remove link

To implement this functionality, you can create a "remove location" feature in your application's user interface. When the user selects a location to remove, you can check the type of location and take the appropriate action:

If the location is 1-1 (i.e. it has only one link), you can delete the node and the link.
If the location is 1-many (i.e. it has multiple links), you can remove the link between the node and its parent, but keep the node itself.
You can also provide feedback to the user after the location has been removed, such as a confirmation message or an updated visualization of the remaining locations.

**Comment by shadow0500** [comment]
**Here is an example which I wrote in python.**
``` python
 locations = {
    "location1": ["location2"],
    "location2": ["location1", "location3"],
    "location3": ["location2"]
}

# Function to remove a location by ID
def remove_location(location_id):
    # Check if the location exists in the dictionary
    if location_id in locations:
        # Check the type of the location
        if len(locations[location_id]) == 1:
            # If it's 1-1, delete the node and link
            connected_location_id = locations[location_id][0]
            del locations[location_id]
            locations[connected_location_id].remove(location_id)
        else:
            # If it's 1-many, remove the link only
            for connected_location_id in locations[location_id]:
                locations[connected_location_id].remove(location_id)
            del locations[location_id]
        print(f"Location {location_id} has been removed.")
    else:
        print(f"Location {location_id} does not exist.")



remove_location("location1")

```

**Comment by alexopenline** [comment]
Remove location from Contact is paused.
Focus moved to remove location from Organizations.
