### ISSUE TITLE
[api] Provide FE with validation message for validated entities

### ISSUE THREAD

**Issue by Kasia9090** [openline-ai/openline-customer-os#2256]
Validation message should be returned to FE for email, phone number and location entities
https://www.figma.com/file/TlaP2WC8UPgVAMB7g08UBL/Spaces-V2?type=design&node-id=664-3319&t=REQnT3MzC2Dhwaoq-0

**Comment by shadow0500** [comment]
> Validation message should be returned to FE for email, phone number and location entities https://www.figma.com/file/TlaP2WC8UPgVAMB7g08UBL/Spaces-V2?type=design&node-id=664-3319&t=REQnT3MzC2Dhwaoq-0

could you please elaborate your issue .
