### ISSUE TITLE
UX quality on Orgs table

### ISSUE THREAD

**Issue by mattbr0wn** [openline-ai/openline-customer-os#2312]
**Describe the bug**

- Reversed words as I type in relationships.
- Disappearing relationship placeholder
- Text selectable inside the suggestions box
- Janky selection in the table itself
- Row height is excessive

**Expected behavior**

Video -> https://openline-ai.slack.com/files/U04CMCN1MR9/F05BCBNMKBP/screenshare_-_2023-06-07_6_49_49_pm.webm

Thank you for your bug report!  We ❤️ squashing 🪲

**Comment by acalinica** [comment]
Row height is excessive - This will be treated in a separate PR.
The other ones will be handled by #2305
