### ISSUE TITLE
Phone number doesn't display

### ISSUE THREAD

**Issue by mattbr0wn** [openline-ai/openline-customer-os#2360]
**Describe the bug**
- Phone number doesn't display on contacts page
- Can't edit phone number to include +44 country code

Details in slack thread:  https://openline-ai.slack.com/archives/C04KV2834V7/p1686667695586799

Thank you for your bug report!  We ❤️ squashing 🪲

**Comment by Kasia9090** [comment]
> Phone number doesn't display on contacts page

This part of the issue is fixed as part of [this mr](https://github.com/openline-ai/openline-customer-os/pull/2362)
