### ISSUE TITLE
[EPIC] - Launch customerOS

### ISSUE THREAD

**Issue by mattbr0wn** [openline-ai/openline-customer-os#25]
- https://github.com/openline-ai/openline-customer-os/issues/29
- https://github.com/openline-ai/openline-customer-os/issues/38
- https://github.com/openline-ai/openline-customer-os/issues/30
- https://github.com/openline-ai/openline-customer-os/issues/31
- https://github.com/openline-ai/openline-customer-os/issues/32
- https://github.com/openline-ai/openline-customer-os/issues/33
- https://github.com/openline-ai/openline-customer-os/issues/34
- https://github.com/openline-ai/openline-customer-os/issues/35
- https://github.com/openline-ai/openline-customer-os/issues/36
- https://github.com/openline-ai/openline-customer-os/issues/37
- https://github.com/openline-ai/openline-customer-os/issues/39
- https://github.com/openline-ai/openline-customer-os/issues/40
- https://github.com/openline-ai/openline-customer-os/issues/41
- https://github.com/openline-ai/openline-customer-os/issues/51
- https://github.com/openline-ai/openline-customer-os/issues/27
- https://github.com/openline-ai/openline-customer-os/issues/43
- https://github.com/openline-ai/openline-customer-os/issues/44
- https://github.com/openline-ai/openline-customer-os/issues/45
- https://github.com/openline-ai/openline-customer-os/issues/46
- https://github.com/openline-ai/openline-customer-os/issues/47
- https://github.com/openline-ai/openline-customer-os/issues/48
- https://github.com/openline-ai/openline-customer-os/issues/50
- https://github.com/openline-ai/openline-customer-os/issues/49
- https://github.com/openline-ai/openline-customer-os/issues/137
- https://github.com/openline-ai/openline-customer-os/issues/140
- https://github.com/openline-ai/openline-customer-os/issues/141
- https://github.com/openline-ai/openline-customer-os/issues/143
- https://github.com/openline-ai/openline-customer-os/issues/144

- bugs : 
- https://github.com/openline-ai/openline-customer-os/issues/99

**Comment by xvasi** [comment]
- Create readme Docs :[ Issue 27](https://github.com/openline-ai/openline-customer-os/issues/27)

**Comment by mattbr0wn** [comment]
customerOS needs to ship with a simple app launcher application.  The app launcher comes pre-loaded with a single app -- Explorer.  Explorer is a simple view-only GUI over the top of customerOS so developers can interact with the data.

**Comment by mattbr0wn** [comment]
converted to milestone
