### ISSUE TITLE
Customer tab in table view needs to filter for Live

### ISSUE THREAD

**Issue by mattbr0wn** [openline-ai/openline-customer-os#2819]
Customers tab in table view should filter on Relationship: Customer && Stage: Live

**Comment by Arya43221** [comment]
Access the "Customers" tab: Navigate to the section or page where the "Customers" table is displayed. It should show a list of customers with various attributes, including "Relationship" and "Stage."

Look for filtering options: Examine the table or the header section for filtering options. Many applications provide filter icons, filter buttons, or search boxes to enable data filtering.

Apply the first filter: Locate the "Relationship" column and look for the filter option associated with it. It may appear as a dropdown menu or a checkbox list. Select "Customer" from the available options to filter the table to show only customers with the "Customer" relationship.

Apply the second filter: Similarly, find the "Stage" column and apply the "Live" filter. This will further refine the table to show only customers who are in the "Live" stage.

Combine filters (if needed): Some applications allow you to combine multiple filters. If this is the case, you might be able to select both "Customer" and "Live" filters simultaneously to achieve the desired result.

Clear filters (if necessary): If there are already filters applied to the table, make sure to clear them before applying the new filters to avoid conflicting results.

Review the filtered table: After applying the filters, review the "Customers" table to ensure it displays only the customers with a "Customer" relationship and are in the "Live" stage

**Comment by avalot** [comment]
Only if the View is called "Live Customers".

We could create a view called Live Customers, and other views for non-live customers. Or we can implement filtering of the Customers view. 

I think we should go from Generic to specific. So for now let's keep the generic "Customers" view, and add "Live Customers" as a preset list later, if we notice our tenants need it.

**Comment by mattbr0wn** [comment]
Customer view as-is is going to be super noisy as all CRM data creates as
customers - prospect...
