### ISSUE TITLE
My Portfolio tab in table view should have additional filters

### ISSUE THREAD

**Issue by mattbr0wn** [openline-ai/openline-customer-os#2821]
Filter should be:

Relationship: Customer
Stage: Live
Owner: Me

**Comment by avalot** [comment]
I challenge that.
 
When Kay manually assigns an organization to Howard, her intent is clear: I want Bob to own this org. In our current system, the way you own an org is through the portfolio list. (Later, there can be other ways).

If Kay assigned a non-customer, or a non-live customer, they, she probably has a good reason. If she later decides she doesn't want that org in Bob's portfolio, she can remove Bob as an owner. It's a quick fix, dependable action: Ownership=>Portfolio

Perhaps she wants Bob to prepare the handoff of an incoming prospect that's about to sign. Perhaps it's a vendor Bob needs to keep track of. Perhaps Bob is managing a partnership... we can't presume.

Also, this enables portfolios for any other function in the company: sales, marketing, legal, product... 

Assuming we keep to that interface for now, we do need to design with the thought in mind: Not every org in the portfolio will be a customer. We might want to make the display of certain data columns, and the calculation of scores, conditional to the org relationship.
