### ISSUE TITLE
My tenant should be filtered out from organization view

### ISSUE THREAD

**Issue by mattbr0wn** [openline-ai/openline-customer-os#2822]
My tenant (e.g. Openline) should be filtered out from organization view.  I don't want to see my org in the table.

**Comment by Arya43221** [comment]
The exact steps to achieve this will depend on the specific application or system you are using. Generally, though, you can follow these steps:

Identify the filtering mechanism: Determine how the organization view or table is generated and what filtering options are available to you. Many applications offer built-in search or filtering features that allow you to search for specific names or exclude certain entries.

Access the organization view or table: Navigate to the section or page where the list of tenants or organizations is displayed.

Apply the filter: Look for a search box or filter options, usually located at the top or side of the table. Enter the name of your organization (e.g., Openline) in the search box and see if it automatically filters out the entry.

Use an exclusion filter (if available): If the search box doesn't filter out your organization or if there's no search option available, check for advanced filtering options. Some applications allow you to apply exclusion filters, which would allow you to exclude a specific entry from the table.

**Comment by alexopenline** [comment]
Marked openline as "tenant organization". API is already filtering out tenant orgs.
