### ISSUE TITLE
Response time degradation between v0.40.4 and v0.41.6

### ISSUE THREAD

**Issue by SilviuOpenline** [openline-ai/openline-customer-os#2956]
Average response time for global_Cache is (255.839 ms)
Average previous response time for global_Cache was (231.248 ms)
Average response time for global_Cache INCREASED by 10.00%

Average response time for gcli_Search is (164.148 ms)
Average previous response time for gcli_Search was (136.091 ms)
Average response time for gcli_Search INCREASED by 20.00%

Average response time for createOrganization is (797.458 ms)
Average previous response time for createOrganization was (690.939 ms)
Average response time for createOrganization INCREASED by 15.00%

Average response time for org-dashboardView_Organizations is (312.357 ms)
Average previous response time for org-dashboardView_Organizations was (282.557 ms)
Average response time for org-dashboardView_Organizations INCREASED by 10.00%

Average response time for emailMergeToContact is (224.828 ms)
Average previous response time for emailMergeToContact was (196.[42](https://github.com/openline-ai/openline-performance-testing/actions/runs/5721814766/job/15503957745#step:8:43)3 ms)
Average response time for emailMergeToContact INCREASED by 14.00%

Average response time for GetHealthIndicators is (200.518 ms)
Average previous response time for GetHealthIndicators was (164.101 ms)
Average response time for GetHealthIndicators INCREASED by 22.00%

Average response time for createUser is ([43](https://github.com/openline-ai/openline-performance-testing/actions/runs/5721814766/job/15503957745#step:8:44)7.654 ms)
Average previous response time for createUser was (397.372 ms)
Average response time for createUser INCREASED by 10.00%

Average response time for organization_SetRelationshipStage is (259.338 ms)
Average previous response time for organization_SetRelationshipStage was (219.067 ms)
Average response time for organization_SetRelationshipStage INCREASED by 18.00%

Average response time for organization_AddRelationship is (289.572 ms)
Average previous response time for organization_AddRelationship was (258.956 ms)
Average response time for organization_AddRelationship INCREASED by 11.00%

Average response time for createContact is (657.001 ms)
Average previous response time for createContact was (557.981 ms)
Average response time for createContact INCREASED by 17.00%

Average response time for createTenant is (966.655 ms)
Average previous response time for createTenant was (891.832 ms)
Average response time for createTenant INCREASED by 8.00%

Average response time for phoneNumberMergeToContact is (228.8[49](https://github.com/openline-ai/openline-performance-testing/actions/runs/5721814766/job/15503957745#step:8:50) ms)
Average previous response time for phoneNumberMergeToContact was (207.976 ms)
Average response time for phoneNumberMergeToContact INCREASED by 10.00%

Average response time for getContact is (272.799 ms)
Average previous response time for getContact was (228.409 ms)
Average response time for getContact INCREASED by 19.00%

Average response time for getUsers is (222.59 ms)
Average previous response time for getUsers was (186.256 ms)
Average response time for getUsers INCREASED by 19.00%

Average response time for organization_SetOwner is (234.415 ms)
Average previous response time for organization_SetOwner was (197.277 ms)
Average response time for organization_SetOwner INCREASED by 18.00%

Average response time for addLocationToOrganization is (253.528 ms)
Average previous response time for addLocationToOrganization was (222.868 ms)
Average response time for addLocationToOrganization INCREASED by 13.00%

Average response time for getOrganization is (257.29 ms)
Average previous response time for getOrganization was (230.936 ms)
Average response time for getOrganization INCREASED by 11.00%

Average response time for location_Update is (238.055 ms)
Average previous response time for location_Update was (201.856 ms)
Average response time for location_Update INCREASED by 17.00%

Average response time for user_AddRole is (187.596 ms)
Average previous response time for user_AddRole was (1[51](https://github.com/openline-ai/openline-performance-testing/actions/runs/5721814766/job/15503957745#step:8:52).717 ms)
Average response time for user_AddRole INCREASED by 23.00%

Average response time for cust-dashboardView_Organizations is (296.14 ms)
Average previous response time for cust-dashboardView_Organizations was (264.426 ms)
Average response time for cust-dashboardView_Organizations INCREASED by 11.00%

**Comment by alexopenline** [comment]
As latests tests have back normal durations I suggest to close this ticket.
Still no changes in mentioned APIs been done recently
