### ISSUE TITLE
Emails are not persisted in the UI

### ISSUE THREAD

**Issue by SilviuOpenline** [openline-ai/openline-customer-os#3047]
**Describe the bug**
After sending an email, no trace of it is displayed in the UI

**Steps**
1. Go to Organizations Page
2. Click on an Organization
3. Send an email

**Expected behavior**
The email should appear at the bottom of the timeline

**Actual behavior**
The area below the timeline remains empty

**Screenshots**
![Screenshot 2023-08-04 at 16 18 12](https://github.com/openline-ai/openline-customer-os/assets/125381623/c85be350-8605-4c92-9e02-bc209bfaf0d3)

**Comment by Kasia9090** [comment]
Timeline event is not returned, we need to check if event is created properly
