### ISSUE TITLE
No BE validation to match the FE validations

### ISSUE THREAD

**Issue by SilviuOpenline** [openline-ai/openline-customer-os#3051]
**Describe the bug**
Values that are validated in the UI are not validated in BE

**Steps**
1. Go to Organizations Page
2. Click on an organization
3. Update the industry

**Expected behavior**
No value should be allowed that is not in the Industry combo box

**Actual behavior**
Any value can be provided if the XHR is replayed using curl with updated values -> there's no validation on BE
![Screenshot 2023-08-04 at 16 46 46](https://github.com/openline-ai/openline-customer-os/assets/125381623/b51322d3-ea78-49b9-bc6c-ea32f948b511)

**Comment by alexopenline** [comment]
BE accepting any value for industry intentionally.
There is the async process in events-platform to match given value to a list of GICS standard.
