### ISSUE TITLE
No labels or hints are present on the icons

### ISSUE THREAD

**Issue by SilviuOpenline** [openline-ai/openline-customer-os#3052]
**Description**
For a new customer, it will be hard to understand what he filled in after the Organization was created as he will only see some icons that can't be related to something.
E.g.: 
"horizontal opened hand that receives a heart" = relationship.
The workaround for a new customer would be to create another empty organization and see what's the text for the icons

![Screenshot 2023-08-04 at 16 58 02](https://github.com/openline-ai/openline-customer-os/assets/125381623/45101dc5-82fd-480b-b35e-81a69aaba17b)

**Comment by steynviljoen67** [comment]
I'd recommend we add a tooltip with the placeholder text on icon hover for now.
