### ISSUE TITLE
Finder table does not bottom align

### ISSUE THREAD

**Issue by steynviljoen67** [openline-ai/openline-customer-os#3189]
**Describe the bug**
The finder table does not currently align to the meta panel card and has a big gap below it

**Expected behavior**
Bottom align the card / remove the gap at the bottom

**Screenshots**
<img width="735" alt="Screenshot 2023-08-15 at 07 57 51" src="https://github.com/openline-ai/openline-customer-os/assets/108709792/5c208b97-24b7-4cb6-90db-2675a5bab336">

**Comment by acalinica** [comment]
fixed in #3111
