### ISSUE TITLE
Comms-api creating orphan interaction sessions

### ISSUE THREAD

**Issue by alexopenline** [openline-ai/openline-customer-os#3199]
Data sample:

(:InteractionSession:InteractionSession_openline {createdAt: 2023-08-15T11:05:20.291290694Z[UTC], identifier: "<CADRw8irZY2pku+C6Mtqr0mCTY5-WSuce1PbzLS_ET0OCLSVKKQ@mail.gmail.com>", sourceOfTruth: "openline", name: "Re: Connecting Silverflow CS leader and Openline", channel: "EMAIL", source: "openline", id: "8cb55231-d5ce-4a7f-8b74-d77a539ac711", appSource: "COMMS_API", type: "THREAD", updatedAt: 2023-08-15T11:05:20.291290694Z[UTC], status: "ACTIVE"})

Node is not linked to any other node.

**Comment by tsearle** [comment]
from investigation of the logs, and interaction event was successfully linked to this interaction session.  manual deletion must have happened later

`{
    "time": "2023-08-15T11:05:20.573691737Z",
    "stream": "stdout",
    "_p": "F",
    "log": "2023-08-15 11:05:20.572   BOLT  [bolt-109912@p-neo4j-e38fe2eb-cb0c2cb6-131.production-orch-0010.neo4j.io:7687] C: RUN \"MERGE (ie:InteractionEvent_openline {id:randomUUID()}) ON CREATE SET   ie:InteractionEvent,   ie:TimelineEvent,   ie:TimelineEvent_openline,  ie.source=$source,  ie.channel=$channel,  ie.channelData=$channelData,  ie.createdAt=$createdAt,  ie.identifier=$identifier,  ie.content=$content,  ie.contentType=$contentType,  ie.eventType=$eventType,  ie.sourceOfTruth=$sourceOfTruth,  ie.appSource=$appSource  RETURN ie\" {\"appSource\":\"COMMS_API\",\"channel\":\"EMAIL\",\"channelData\":\"{\\\"Subject\\\":\\\"Re: Connecting Silverflow CS leader and Openline\\\",\\\"InReplyTo\\\":[\\\"\\\\u003cCAJU9xZhA-pTNmZA4t6WtZQKTVYfYhjGMLkSq_zAWLRbJ0g6jsg@mail.gmail.com\\\\u003e\\\"],\\\"Reference\\\":[\\\"\\\\u003cCADRw8irZY2pku+C6Mtqr0mCTY5-WSuce1PbzLS_ET0OCLSVKKQ@mail.gmail.com\\\\u003e\\\",\\\"\\\\u003cC0821AC9-49BE-4343-B1A4-686CCEB84D83@silverflow.com\\\\u003e\\\",\\\"\\\\u003cCAJU9xZiLKs-seFTYxnfX=Ofd4OcoNCS2U_wPV=1YAW5Dvw7SXg@mail.gmail.com\\\\u003e\\\",\\\"\\\\u003cCAJU9xZgZYR7yhfsNG3zePs7mqc7eyDUtNNEvX0MKDXFFd33E8A@mail.gmail.com\\\\u003e\\\",\\\"\\\\u003cC42EC248-8101-4AF8-ABA5-0999D8E5A25D@silverflow.com\\\\u003e\\\",\\\"\\\\u003cCAJU9xZhA-pTNmZA4t6WtZQKTVYfYhjGMLkSq_zAWLRbJ0g6jsg@mail.gmail.com\\\\u003e\\\"]}\",\"content\":\"***censored****",\"contentType\":\"multipart/alternative; boundary=\\\"0000000000007a86b50602f427b0\\\"\",\"createdAt\":\"2023-08-15T11:05:20.572405544Z\",\"eventType\":null,\"identifier\":\"<CAJU9xZhOYtjXiKTjyo9ZwQ9zOQHNUaOCo5noiKp-FRvW21TMbg@mail.gmail.com>\",\"source\":\"openline\",\"sourceOfTruth\":\"openline\",\"tenant\":\"openline\"} null",
    "kubernetes": {
        "pod_name": "ainers.customer-os-api-78f8b959b-l2nxs",
        "namespace_name": "openline",
        "container_name": "customer-os-api",
        "docker_id": "9c60bd0b9db1c38cc6791a8ef001c7aae918c83820455f14988a2634503d8538"
    }
}`

**Comment by tsearle** [comment]
```
{
    "time": "2023-08-15T11:05:20.593520164Z",
    "stream": "stdout",
    "_p": "F",
    "log": "2023-08-15 11:05:20.593   BOLT  [bolt-109912@p-neo4j-e38fe2eb-cb0c2cb6-131.production-orch-0010.neo4j.io:7687] S: RECORD [{\"Id\":8441,\"ElementId\":\"4:9911eaca-fdc0-4faa-9ecc-9bf88249b7de:8441\",\"Labels\":[\"TimelineEvent\",\"InteractionEvent_openline\",\"InteractionEvent\",\"TimelineEvent_openline\"],\"Props\":{\"appSource\":\"COMMS_API\",\"channel\":\"EMAIL\",\"channelData\":\"{\\\"Subject\\\":\\\"Re: Connecting Silverflow CS leader and Openline\\\",\\\"InReplyTo\\\":[\\\"\\\\u003cCAJU9xZhA-pTNmZA4t6WtZQKTVYfYhjGMLkSq_zAWLRbJ0g6jsg@mail.gmail.com\\\\u003e\\\"],\\\"Reference\\\":[\\\"\\\\u003cCADRw8irZY2pku+C6Mtqr0mCTY5-WSuce1PbzLS_ET0OCLSVKKQ@mail.gmail.com\\\\u003e\\\",\\\"\\\\u003cC0821AC9-49BE-4343-B1A4-686CCEB84D83@silverflow.com\\\\u003e\\\",\\\"\\\\u003cCAJU9xZiLKs-seFTYxnfX=Ofd4OcoNCS2U_wPV=1YAW5Dvw7SXg@mail.gmail.com\\\\u003e\\\",\\\"\\\\u003cCAJU9xZgZYR7yhfsNG3zePs7mqc7eyDUtNNEvX0MKDXFFd33E8A@mail.gmail.com\\\\u003e\\\",\\\"\\\\u003cC42EC248-8101-4AF8-ABA5-0999D8E5A25D@silverflow.com\\\\u003e\\\",\\\"\\\\u003cCAJU9xZhA-pTNmZA4t6WtZQKTVYfYhjGMLkSq_zAWLRbJ0g6jsg@mail.gmail.com\\\\u003e\\\"]}\",\"content\":\"***CENSORED***\"\,contentType\":\"multipart/alternative; boundary=\\\"0000000000007a86b50602f427b0\\\"\",\"createdAt\":\"2023-08-15T11:05:20.572405544Z\",\"id\":\"d3f90d5b-3719-4152-b3c2-0138b93510cc\",\"identifier\":\"<CAJU9xZhOYtjXiKTjyo9ZwQ9zOQHNUaOCo5noiKp-FRvW21TMbg@mail.gmail.com>\",\"source\":\"openline\",\"sourceOfTruth\":\"openline\"}}]",
    "kubernetes": {
        "pod_name": "ainers.customer-os-api-78f8b959b-l2nxs",
        "namespace_name": "openline",
        "container_name": "customer-os-api",
        "docker_id": "9c60bd0b9db1c38cc6791a8ef001c7aae918c83820455f14988a2634503d8538"
    }
}
```

**Comment by tsearle** [comment]
not a bug, manual deletion occured
