### ISSUE TITLE
Inspect dropshadow styling and ensure they are the same across app

### ISSUE THREAD

**Issue by Kasia9090** [openline-ai/openline-customer-os#3233]

**Comment by steynviljoen67** [comment]
@Kasia9090 here are screenshots of how the timeline dropshadow is different from the tab cards.

The timeline cards need to have the same styling as the cards in the left panel.

<img width="1056" alt="Screenshot 2023-08-17 at 11 02 27" src="https://github.com/openline-ai/openline-customer-os/assets/108709792/1c269fdb-4ff4-4cd9-a99e-f86888b5a860">
<img width="1042" alt="Screenshot 2023-08-17 at 11 02 42" src="https://github.com/openline-ai/openline-customer-os/assets/108709792/1a08553a-55c9-438e-85a4-4a7a9560826b">
