### ISSUE TITLE
Slack UI tweaks

### ISSUE THREAD

**Issue by steynviljoen67** [openline-ai/openline-customer-os#3287]
- [x] #3330
- [x] Add 1px (primary-200) border to empty avatars. [Design reference](https://www.figma.com/file/QsyWtRJW9eoLB7eZkVY8y7/Timeline?type=design&node-id=819-44780&mode=design&t=nWHLHXrPpHA1eBix-4)
- [x] Reduce avatars to 40px
- [x] Reduce padding between contact name and message
-  Show full colour slack icon on the right and change border colour to Gray-100 [won't fix]
-  Hover over the slack icon can be a default arrow cursor until we have the link to the channel [won't fix]
- [x] Reduce the "x replies" font size to SM (12px) and remove underline on hover
- [x] Hovering over cards in the preview should have the text cursor (text hover) and pointer (avatar or card background hover), not the hand cursor
- [x] Can we bump up the font size of the "Thread" heading in preview to LG (18px) instead of 16px. This is applicable to the headings on Email previews as well
- [x] #3288

**Comment by Kasia9090** [comment]
>  Show full colour slack icon on the right and change border colour to Gray-100
> Hover over the slack icon can be a default arrow cursor until we have the link to the channel

those two are related to state of the button (disabled). Buttons will be enables as soon as link to slack channel will be provided. I'll mark them as won't fix
