### ISSUE TITLE
Contact - save custom fields

### ISSUE THREAD

**Issue by edifirut** [openline-ai/openline-customer-os#331]
Having this EntityDefinition
`{
        "id": "0ba4870a-059c-4196-a9fe-62f0ef3f86ba",
        "name": "CONTACT_CLINIC",
        "extends": "CONTACT",
        "fieldSets": [
          {
            "id": "fc027358-cc3e-47aa-923e-70a0db9ad197",
            "name": "Clinic fieldset",
            "order": 2,
            "customFields": [
              {
                "id": "e4d1641b-23d3-441f-be04-cc1920981db5",
                "name": "field in Clinic fieldset",
                "type": "TEXT",
                "order": 1,
                "mandatory": false,
                "length": 255,
                "min": null,
                "max": null
              }
            ]
          }
        ],
        "customFields": [
          {
            "id": "be85157f-a133-4087-8ed4-ec3f899d173b",
            "name": "clinic field 1",
            "type": "TEXT",
            "order": 1,
            "mandatory": false,
            "length": 255,
            "min": null,
            "max": null
          }
        ]
      }`

Trying to create a contact with the below query
`curl 'http://localhost:10000/query' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-US,en;q=0.9,ro;q=0.8' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost:3000' \
  -H 'Referer: http://localhost:3000/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'sec-ch-ua: "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw $'{"query":"mutation CreateContact($contact: ContactInput\u0021) {\\n            contact_Create(input: $contact) {\\n                id\\n            }\\n        }","variables":{"contact":{"title":"MR","firstName":"1","lastName":"1","contactTypeId":"78f2f1d1-330e-43cd-ab62-4f058303a3b5","label":"","notes":"","definitionId":"0ba4870a-059c-4196-a9fe-62f0ef3f86ba","customFields":[{"value":"","name":"clinic field 1","datatype":"TEXT","definitionId":"be85157f-a133-4087-8ed4-ec3f899d173b"}],"fieldSets":[{"name":"Clinic fieldset","definitionId":"fc027358-cc3e-47aa-923e-70a0db9ad197","customFields":[{"value":"","name":"field in Clinic fieldset","datatype":"TEXT","definitionId":"e4d1641b-23d3-441f-be04-cc1920981db5"}]}]}},"operationName":"CreateContact"}' \
  --compressed`

Doesn't store the custom fields from the field sets. If i sent a value, it's going to store the fields in the field set

**Comment by alexopenline** [comment]
@edifirut 

Based on graphql definition of CustomFieldInput
`Datatype of the custom field.
Required
[value]: [Any]!`

"value" is required to be specified in custom field input.
Can be left as empty string if custom field to be present but without any value

If custom field should not be present, then whole custom field input object should not be sent.

**Comment by edifirut** [comment]
@alexopenline we need to save the fields with empty value on contact creation. we need to make a print of the entity definition at creation time. so, we need to remove that. i should be able to save am empty custom field that comes from a definition ( the custom fields added manually can't be saved with an empty value )
