### ISSUE TITLE
Finder tweaks

### ISSUE THREAD

**Issue by steynviljoen67** [openline-ai/openline-customer-os#3315]
- [x] Update website text hover ([design](https://www.figma.com/file/uWolaNIV9vDhQ5PfQGNC7o/Finder?type=design&node-id=157-565&mode=design&t=sFla4cylKVSSBM4L-4))
- [x] Update dropdown hover styling on select and menus to primary-50 ([design reference](https://www.figma.com/file/GGd3IzUsi6INf7n6BHdjdX/Org-Tabs?type=design&node-id=887-1151&mode=design&t=0HU44oIBoRmHdA4e-4)) 
 - Besides the hover colour, Menus don't have to get any other styling changes based on the conversation we had via Slack

**People tab**
- [x] For the Role field on People tab, interaction should be the following:
* Clicking the field, expands card
* Show dropdown immediately (currently I need to click again
* Once an option is selected, keep dropdown open

**Comment by steynviljoen67** [comment]
We can revisit date formatting like this in the future:
 - [ ] For the "How long ago" and Renewal likelihood field, can we use the following date format
Seconds ago
1 minute ago / 21 minutes ago
1 hour ago / 21 hours ago
1 day ago / 21 days ago
1 week ago / 3 weeks ago
1 month ago / 11 months ago
1 year ago / 3 years ago

**Comment by acalinica** [comment]
closed by #3337
