### ISSUE TITLE
Empty Billing details resets Renewal forecast

### ISSUE THREAD

**Issue by SilviuOpenline** [openline-ai/openline-customer-os#3560]
**Steps**
1. Go to Organizations>Company>Account and set a value for Renewal forecast
2. Go to Organizations
3. Go to Organizations>Company>Account and Click the Value of the Billing amount value (empty) under Billing details
4. Click out of the Billing amount value

**Expected behavior**
No change should appear on the page

**Actual behavior**
Renewal forecast is cleared

**Comment by alexopenline** [comment]
Expected behavior
