### ISSUE TITLE
Slack UI polish

### ISSUE THREAD

**Issue by steynviljoen67** [openline-ai/openline-customer-os#3612]
Double check that the Slack Code and Code block border colour is Gray-300
- [ ] Change Slack icon border colour on cards to be Gray-100 (this is applicable to Intercom integration as well)
- [ ] Center align the Slack timestamp with the contact name (both timeline and preview)
- [ ] Increase padding between Slack Replies and avatars to 8px

**Comment by Sam-Radnus** [comment]
can I take this task

**Comment by steynviljoen67** [comment]
> can I take this task

@acalinica @Kasia9090 what would Sam need to pick up this task?

**Comment by Kasia9090** [comment]
This task should be marked as done, it was created while we were moving to linear for task management and therefore duplicated in github issues and linear @Sam-Radnus @steynviljoen67

**Comment by steynviljoen67** [comment]
All good. Anything else Sam could pick up?

Possibly this one? https://linear.app/customer-os/issue/COS-30/implement-linking-of-text-in-rich-editor

Or this one: https://linear.app/customer-os/issue/COS-186/update-order-of-renewal-likelihood-tab-control
