### ISSUE TITLE
Test email tracker w/ loops

### ISSUE THREAD

**Issue by matt-brown-OL** [openline-ai/openline-customer-os#4]

**Comment by alexopenline** [comment]
Tracker hit to be injected in email:
<img src="<COLLECTOR_URL>/com.snowplowanalytics.iglu/v1?schema=iglu%3Aai.openline%2Femail_open%2Fjsonschema%2F1-0-0&aid=<APP ID>&trna=<TRACKER NAME>&emailId=<EMAIL CAMPAIGN ID>&recipientId=<RECIPIENT EMAIL OR NAME>"/>
