### ISSUE TITLE
New `Place`, `Location`, `Person`, & in-person meeting nodes

### ISSUE THREAD

**Issue by mattbr0wn** [openline-ai/openline-customer-os#636]
- Place
   - Address
      - Address Line 1
      - Address Like 2
      - City
      - State
      - Region
      - Country
      - PlaceName
   - Coordinates
      - Lat/Lon
      - Radius
   - Area (in the future)
      - Zone polygon(s)
      - Lat/Lon points
      
- Org
   - Location(s) (one-to-many)
      - LocationType (HQ, Office, store, church, factory, home, warehouse, dock, etc.)
      - LocationName (“Vasi’s home”)
      - Place (1-to-1)
- Person
   - Location(s) (one-to-many)
      - LocationType
      - LocationName
      - Place (1-to-1)

New communication event for in-person meeting that links to Locations (and thus Orgs), and Persons

**Comment by avalot** [comment]
I'm guessing "Person" is our new name for "Contact", right?

**Comment by mattbr0wn** [comment]
I think it has to be.  And this ripples out to the UI as well.  You don't call a contact, you call a person.

**Comment by alexopenline** [comment]
Do we agree to rename all APIs and graph DB from Contact -> Person ?

**Comment by alexopenline** [comment]
https://www.figma.com/file/oyThaaVpNWgNHr63kZprkM/GraphDB-Nodes-%26-Relations?node-id=0%3A1&t=NmeV1kELbX6OK6N2-0
