### ISSUE TITLE
Add fields to EmailContent in sync_service

### ISSUE THREAD

**Issue by gabriel0003** [openline-ai/openline-customer-os#686]
We have an EmailContent structure in oasis and we have an EmailContent structure in sync_service.

https://github.com/openline-ai/openline-oasis/blob/7e32eadb766c0c88b3f44baade216e8271aed3d5/packages/server/channels-api/routes/mail.go#L83

https://github.com/openline-ai/openline-customer-os/blob/32c4dc2b48a5f7a2b7401a469016e261d12fa4b6/packages/runner/sync-customer-os-data/service/sync_service.go#L484
These structure need to be in sync for now (we'll find a sharing mechanism in the monorepo).

In order to support sending and replying to emails in oasis we added these fields in EmailContent:
 
MessageId
InReplyTo
Reference

What needs to happen how is to find the equivalent fields in hubspot and sync them.

**Comment by alexopenline** [comment]
MessageId implemented in https://github.com/openline-ai/openline-customer-os/issues/697
