### ISSUE TITLE
Ability to log a communication against a contact

### ISSUE THREAD

**Issue by mattbr0wn** [openline-ai/openline-customer-os#745]
As a B2C company, I’d like the ability to log communication against a contact.  I should be able to log the following types of communications:

- Voice call
- SMS
- Video call
- LinkedIn message
- Whatsapp message
- Telegram message
- Twitter DM and public @ post
- Instagram message
- Meeting
- Email
- Note

**Comment by Kasia9090** [comment]
To deliver this feature I need:
1. contract on gql data schema for all listed types besides email and note  (cc. @alexopenline)
2. rough idea on how those communication entries should be presented to the end user (cc. @avalot)

**Comment by Kasia9090** [comment]
@mattbr0wn are all of those communication types part of the mvp? If so, I need message content schema for each one of them
