### ISSUE TITLE
Sentry

### ISSUE THREAD

**Issue by edifirut** [openline-ai/openline-customer-os#755]
✗ Your `package.json` specifies a version of `next` outside of the compatible version range >=10.0.8 <13.0.0.

https://docs.sentry.io/platforms/javascript/guides/nextjs/

**Comment by Kasia9090** [comment]
The error that was previously reported appears to have been resolved. The Sentry setup has been completed successfully. Any future issues with Sentry should be considered as bugs and reported accordingly.
