### ISSUE TITLE
[GUI] Add title to pages of GUI

### ISSUE THREAD

**Issue by jontyk** [openline-ai/openline-customer-os#770]
**Overview of the feature request and the problem you're looking to solve**
Update the <head><title> of the page so that it shows:

For Finder: Name of current list:
![image](https://user-images.githubusercontent.com/831133/222738782-fab478de-cce2-411c-b987-33556a20fe8a.png)

When a search is being performed: Key being searched, in quotes, followed by "search":
![image](https://user-images.githubusercontent.com/831133/222739102-23a319fc-6e34-4d55-afc2-f893e3dfded3.png)

For an Org detail, the org name:
![image](https://user-images.githubusercontent.com/831133/222739196-5c48ff10-51a1-450d-baea-9700145d6d0e.png)

For a contact detail, the contact name, followed by a bullet "•" and the org name
![image](https://user-images.githubusercontent.com/831133/222739769-2830aef3-3ef2-46d7-b072-adf6338d294d.png)

If multiple orgs or no org, just the contact name.
![image](https://user-images.githubusercontent.com/831133/222739908-4c57a2b2-32cf-4a4a-a27e-45dbba3b4f76.png)

If no contact name, their email address
![image](https://user-images.githubusercontent.com/831133/222741622-0249b894-76c1-4c37-9049-51ee15136ff4.png)

If no email address, their phone number, followed by "(Unnamed contact)"
![image](https://user-images.githubusercontent.com/831133/222741837-f56017de-56e7-498a-9206-0f70cb039a3e.png)

**Describe the solution you'd like**
Title of page should change based on current thing shown

**Additional context**
Imagine a scenario where our user has 25 Openline tabs open. Let's make their life easier!

Thank you for your feature request!  We strive to make the product better every day, and your input helps!

**Comment by avalot** [comment]
To be clear: We mean the <TITLE> attribute, that shows up in the browser tabs.
