### ISSUE TITLE
Filter web application data by session params

### ISSUE THREAD

**Issue by alexopenline** [openline-ai/openline-customer-os#82]
Add filtering of pages and sessions by session parameters such as:
* Country
* Region
* City
* Device
* Browser
* Browser with version
* OS
* OS with version
* UTM fields
* Entry page
* Exit page
* Source / channel

Multiple filters to be supported.

**Comment by Kasia9090** [comment]
@alexopenline @jontyk What needs to be done in order to complete this issue?
