### ISSUE TITLE
bugfix: adding tags is disabled occasionally

### ISSUE THREAD

**Issue by fedhacks** [openline-ai/openline-customer-os#9122]
**Describe the bug**
Sometimes, you'll add tags and come back to see that you can no longer add tabs. Refreshing the page does not solve the issue, logging out and logging back in does.

**How to reproduce**
1. Create an org
2. Add tags (only happens to the most recently created organization)
3. Switch to a different tab and see if adding tags gets disabled (it happens sporadically)
4. Refresh to confirm that it's still disabled

**Expected behavior**
Not disable adding tags.

**Screenshots**
![Screenshot 2024-10-02 at 12 19 02 PM](https://github.com/user-attachments/assets/5bc069c0-2d6d-4275-8996-f302ff3832f5)

**Additional context**

Thank you for your bug report!  We ❤️ squashing 🪲

**Comment by acalinica** [comment]
@fedhacks Thanks for raising this. We'll look into.

**Comment by steynviljoen67** [comment]
@fedhacks this should be fixed now. Let us know if it didn't address your issue.
