### ISSUE TITLE
bugfix: editing company name within organization view changes org website 

### ISSUE THREAD

**Issue by fedhacks** [openline-ai/openline-customer-os#9123]
**Describe the bug**
Editing company name within organization view changes org website + no clear place to change org website within org view 

**How to reproduce**
1. Add a url that doesn't populate the org with enrichment data, I used https://dovetailsoftware.com. Because it did not populate the org with enrichment data, you need to add a name.

![Screenshot 2024-10-02 at 3 14 25 PM](https://github.com/user-attachments/assets/6b1e4b7e-e7ae-4580-8d80-82388f724a87)

3. Click the row to enter org view and change the name.

4. Notice how there's no field in the org view to enter the website URL.

![Screenshot 2024-10-02 at 3 14 43 PM](https://github.com/user-attachments/assets/9e3a690e-bb7b-422d-8051-2f5f6962d721)

5. Go back to table view and see that the website URL has changed to whatever you input as company name in step #2 

![Screenshot 2024-10-02 at 3 15 58 PM](https://github.com/user-attachments/assets/b566ef95-8c38-409e-b2db-a8375bdc3e1d)

**Expected behavior**

There are few expected behaviors here. 

1. That users can edit company names from table view

2. That editing company names within org view changes the company name and not the URL name

3. A field to add the company website URL

**Screenshots**

**Additional context**

Thank you for your bug report!  We ❤️ squashing 🪲

**Comment by fedhacks** [comment]
Please close this if I'm off the mark. After another look, the real bug is 1) the company name is meant to be populated with a URL but if it cannot find the company then you're out of luck and stuck dealing with the above.

**Comment by steynviljoen67** [comment]
Thanks for raising the issue. I see that the organization name ended up in the website URL field. This is the field order:
![Screenshot 2024-10-03 at 09 23 16](https://github.com/user-attachments/assets/f4db10f4-bbdf-4324-902c-0ceeb4155c93)

Can you confirm that you added the URL in the Organization website field? Like this:
![Screenshot 2024-10-03 at 09 20 48](https://github.com/user-attachments/assets/2b99031c-1e8d-448c-beb8-d029e17c0756)

**Comment by fedhacks** [comment]
Hi steyn,

Thank you. It seems it finally did get populated. However, I'd like to be able to change the name of the organization myself. 

For example, I would like to name it "Custom Dovetail Software Name" instead of the name it enriches it with.

A better example would be if I was selling to different groups within an org. Let's say I want to sell different offices of an advisory. When I add the URL after the initial organization creation, it will change the name I had originally typed in and then kinda fights with me when I try to change it. 

![Export-1727942034375](https://github.com/user-attachments/assets/197ba1fe-10b9-449d-a003-59ccd56589cc)

**Comment by steynviljoen67** [comment]
I see, that is indeed a nasty bug. Will sort it out. Thanks.

**Comment by alexopenline** [comment]
Solved and released: https://github.com/customeros/customeros/releases/tag/v0.54.146
