### ISSUE TITLE
searching for organization records by url or domain name doesn't always return matching organization

### ISSUE THREAD

**Issue by danielsgriffin** [openline-ai/openline-customer-os#9143]
**Describe the bug**

Sometimes you can search organization records by domain name but not always.

**How to reproduce**

Create Organization records:
- CustomerOS https://customeros.ai/
- Google https://www.google.com/

Open these links:
- https://app.customeros.ai/finder?preset=4661&search=customeros.ai => CustomerOS org record
- https://app.customeros.ai/finder?preset=4661&search=google.com => NOT Google org record 

**Expected behavior**

Expect to be able to search domain name (and even domain URL) to get the matching organization (full URL is stored in the Website field).

**Screenshots**

Added:
<img width="480" alt="image" src="https://github.com/user-attachments/assets/fd8e5633-bf09-4fc3-bb50-f719e958e296">

Search success:
<img width="330" alt="image" src="https://github.com/user-attachments/assets/7a6974ae-c7a8-4322-be32-d3cfc57cb078">

Search failure:
<img width="322" alt="image" src="https://github.com/user-attachments/assets/55dc6ae1-9da1-4f69-a449-2b004876d631">

**Additional context**

Use case: Clicking links automatically created in my prospecting browser extension to open CustomerOS to the finder with the domain of the website in the search param.

Thank you for your bug report!  We ❤️ squashing 🪲

**Comment by danielsgriffin** [comment]
My use case will not actually work anyways. It seems like the url will always reset the query parameter to the most recent search conducted through the website. Opening a new tab with a different query parameter is simply reset.

**Comment by SilviuOpenline** [comment]
@danielsgriffin 
Thank you for raising this.
The current version of the application only allows the search by organization name (as the placeholder says). We will implement in the near future the ability to search by websites.

**Comment by steynviljoen67** [comment]
Hi Daniel, you can now search for website and LinkedIn in the organizations table as well.
