### ISSUE TITLE
bugfix: sort and filters not working

### ISSUE THREAD

**Issue by fedhacks** [openline-ai/openline-customer-os#9162]
**Describe the bug**
Sort by and filters on org view is not working

**How to reproduce**
1. Go to organizations
2. Click on arrows to sort by
3. Click and select different filters

**Expected behavior**
The orgs should reorder by the sort by and filters

**Screenshots**

![sort by and filters not working](https://github.com/user-attachments/assets/229f55ad-824f-4c98-b845-c26380e9cacb)

**Additional context**

**Comment by steynviljoen67** [comment]
We're fixing it now.

**Comment by steynviljoen67** [comment]
This is now fixed
