### ISSUE TITLE
in the create new contact modal the filter for the contact organization is case sensitive

### ISSUE THREAD

**Issue by danielsgriffin** [openline-ai/openline-customer-os#9163]
**Describe the bug**
The filter is not case insensitive. This is a bug because it violates expectations.

**How to reproduce**
1. Go to Contacts.
2. Click on + to open Create new contact modal
3. Try typing in the organization filter with a different casing than in the records

**Expected behavior**
I expect `CU` or `cu` to not filter out `CustomerOS`. Since many companies brand themselves in distinctive ways in their capitalization it can be useful to search for them in all lowercase rather than remembering the exact case.

**Screenshots**

<img width="438" alt="image" src="https://github.com/user-attachments/assets/ab8ee297-c63c-4d45-b862-b9939519975c">

**Additional context**

Thank you for your bug report!  We ❤️ squashing 🪲

**Comment by steynviljoen67** [comment]
Thanks, we're looking at it.

**Comment by steynviljoen67** [comment]
This is fixed now, Daniel.
