### ISSUE TITLE
bug: setting a date for a reminder picks one day behind what I select

### ISSUE THREAD

**Issue by skeptrunedev** [openline-ai/openline-customer-os#9164]
**Describe the bug**

Clicking Oct 8 here, sets the date to Oct 7 when I try to make a reminder in the `/organization/{id}` detail view.

![image](https://github.com/user-attachments/assets/ce5f8d49-71d3-4cad-a644-e3640813f08e)

**Expected behavior**

Date is set to what I click on. 

Thank you for your bug report!  We ❤️ squashing 🪲

**Comment by steynviljoen67** [comment]
We found the problem and will fix it.

**Comment by steynviljoen67** [comment]
After further investigation, it seems like we misclassified the problem. When you chose 8 Oct from the date picker, did you see 7 Oct on the reminder sticky note in the UI?

**Comment by steynviljoen67** [comment]
@skeptrunedev just a bump up on the above 👆🏻

**Comment by jontyk** [comment]
Have reproduced - will fix asap.

**Comment by jontyk** [comment]
This is now fixed.
