### ISSUE TITLE
bugfix: tags not sticking

### ISSUE THREAD

**Issue by fedhacks** [openline-ai/openline-customer-os#9192]
**Describe the bug**
When adding tags, there's a back-and-forth behavior when selecting them.

**How to reproduce**
1. Go to an organization and add tags
2. Search and add desired tags. After 2-3 tags is when it seems to bug out more consistently.
3. Add additional tags and wait to see the tag disappear. Clicking out of the tag field, navigating to another page, will also sometimes delete the tag.
5. See error

**Expected behavior**
Expected behavior is that selected tags *stick* to the field 

**Screenshots**
![Export-1728328005811](https://github.com/user-attachments/assets/2f0c897b-54c0-4ff7-b275-eead41cd36c0)

**Additional context**

**Comment by steynviljoen67** [comment]
We're looking into it, thanks

**Comment by mattbr0wn** [comment]
This is now resolved!
