### ISSUE TITLE
bugfix: contacts disappear from org sporadically

### ISSUE THREAD

**Issue by fedhacks** [openline-ai/openline-customer-os#9193]
**Describe the bug**
Unfortunately, sometimes I go back to an organization to add tags and whatnot and see that the contacts I had just added disappear.

**How to reproduce**
1. Create and organization
2. Add several contacts 
3. Navigate away and come back to it later
4. See error (it happens sporadically, but of course this is painful!)

**Expected behavior**
That my contacts stay put.

**Screenshots**

![Screenshot 2024-10-07 at 12 23 05 PM](https://github.com/user-attachments/assets/205eb1d5-d946-4d24-b4ca-f4e6796d6947)

**Additional context**

**Comment by steynviljoen67** [comment]
Thanks, we found the issue and busy fixing it.

**Comment by mattbr0wn** [comment]
this is now resolved!
