### ISSUE TITLE
Finder view improvements

### ISSUE THREAD

**Issue by Kasia9090** [openline-ai/openline-customer-os#957]
This is a collective issue for ui/ux improvements in Finder screen

**Comment by jontyk** [comment]
All of the following are notes, should be confirmed with @avalot first before implementation.

- Should include total number of entries (both with and without search) so user knows how far infinite scroll will go and if user should refine search
- Chat widget should not move when sidebar is expanded (ideally we should show the 'How can I help?' dialog without the hoverover when the sidebar is expanded)
- If we aren't going to slide the main screen right when sidebar is expanded, we should apply a grey transparent layer to main screen to indicate that the sidebar should be interacted with or minimised before continuing with main view.
- Emails should have blue colour and underline on hover removed to make sure `mailto:` behaviour isn't inferred by user
- Slightly less padding and smaller font size on each row could be better - list currently takes a lot of space per line
- Zebra striping of rows would help also

**Comment by Kasia9090** [comment]
> Chat widget should not move when sidebar is expanded (ideally we should show the 'How can I help?' dialog without the hoverover when the sidebar is expanded)

The ideal version needs updated in chat widget as well. I will extract that part to [separate issue](https://github.com/openline-ai/openline-customer-os/issues/1025)

cc. @jontyk
